

	<div class="row">
		<div class="col-lg-8">
			<?php foreach($this->pages as $pages) : ?>
			<!-- blog entry -->
			<h1><?php echo $this->escape($pages->name);?></a>
			</h1>
			<p class="lead">by <?php echo $this->escape($pages->title);?>
			</p>
			<hr>
			<p>
				<span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
			<hr>
			<img src="public/images/logo/<?php echo $this->escape($pages->ref_logo);?>">
			<hr>
			<p><?php echo $this->escape($pages->body);?></p>
			<a class="btn btn-primary" href="<?php echo $this->url(array(
				'controller' => 'index',
				'action' => 'szczegoly',
				'id' => $pages['id']
			)); ?>">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

			<hr>
			<?php endforeach; ?>

			<!-- pager -->
			<ul class="pager">
				<li class="previous"><a href="#">&larr; Older</a>
				</li>
				<li class="next"><a href="#">Newer &rarr;</a>
				</li>
			</ul>

		</div>

		<div class="col-lg-4">

			<!-- /well -->

			<!-- /well -->

		</div>
	</div>

	<hr>



