

	<div class="row">
		<div class="col-lg-8">

			<!-- the actual blog post: title/author/date/content -->
			<h1><?php echo $this->oPages->name; ?></h1>
			<p class="lead">by <a href="index.php"><?php echo $this->oPages->title; ?></a>
			</p>
			<hr>
			<p>
				<span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
			<hr>
			<img src="/public/images/logo/<?php echo $this->oPages->ref_logo;?>">
			<hr>
			<p class="lead"><?php echo $this->oPages->body; ?></p>


			<hr>





		</div>



