<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Blog Home Template for Bootstrap 3</title>

	<!-- Bootstrap core CSS -->
	<link href="<?php echo $this->baseUrl;?>/public/styles/bootstrap.css" rel="stylesheet">

	<!-- Add custom CSS here -->
	<link href="<?php echo $this->baseUrl;?>/public/styles/blog-home.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl;?>/public/styles/blog-post.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl;?>/public/styles/shop-homepage.css" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Strona Główna</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li><a href="/produkty">Produkty</a>
				</li>
				<?php foreach($this->strony as $strony) : ?>
				<li><a href="<?php echo $this->url(array(
						'controller' => 'index',
						'action' => 'strona',
						'id' => $strony['str_id']
					)); ?>"><?php echo $this->escape($strony->str_nazwa);?></a>
				</li>
				<?php endforeach; ?>
				<?php
				$online = $this->escape($this->online);
				$odnosnik =  $this->escape($this->odnosnik);

				if( $online == 2  )
				{?>
					<li><a href="/<?php echo $odnosnik ?>"><?php echo $odnosnik ?></a></li>
				<?php } ?>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>
<div class="container">
<?php echo $this->layout()->content; ?>
<!-- /.container -->
<footer>
	<div class="row">
		<div class="col-lg-12">
			<p>Copyright &copy; M.Staszowski 2014</p>
		</div>
	</div>
</footer>
</div>
<!-- JavaScript -->
<script src="js/jquery-1.10.2.js"></script>
<script src="js/bootstrap.js"></script>

</body>

</html>
