<form action="/szukaj/wyniki" method="post">
    Wybierz metodę wyszukiwania:<br />
    <select name="metoda_szukania">
      <option value="pro_tytul">Tytuł
      <option value="pro_autor">Autor
      <option value="pro_cena">Cena
    </select>
    <br />
    Wprowadź poszukiwane wyrażenie:<br />
    <input name="wyrazenie" type="text">
    <br />
    <input type="submit" value="Szukaj">
  </form>