<form action="<?php echo $this->baseUrl ?>/admin/<?php
      echo $this->action; ?>" method="post">
   <div>
      <label for="name">Name</label> 
      <input type="text" name="name" value="<?php
         echo $this->escape(trim($this->pages->name));?>"/>
   </div>
   <div>
      <label for="body">body</label> 
      <input type="text" name="body" value="<?php
         echo $this->escape(trim($this->pages->body));?>"/>
   </div>
   <div>
      <label for="title">Title</label>
      <input type="text" name="title" value="<?php
         echo $this->escape($this->pages->title);?>"/>
   </div>

	<div class="row">
		<label for="ref_logo" name="ref_logo">Wybierz logo wpisu (jpg): </label>
		<?php echo $this->formFile( 'ref_logo' ); ?>
	</div>
   <div id="formbutton">
      <input type="hidden" name="id" value="<?php
         echo $this->pages->id; ?>" /> 
      <input type="submit" name="add" value="<?php
         echo $this->escape($this->buttonText); ?>" />
   </div>
</form>