
	<h1><?php echo $this->escape($this->title); ?></h1>

<?php if ($this->pages) :?>
	<form action="<?php echo $this->baseUrl ?>/admin/delete" method="post">
		<p>Are you sure that you want to delete '
			<?php echo $this->escape($this->pages->title); ?>' by '
			<?php echo $this->escape($this->pages->name); ?>'? </p>
		<div>
			<input type="hidden" name="id" value="<?php
			echo $this->pages->id; ?>" />
			<input type="submit" name="del" value="Yes" />
			<input type="submit" name="del" value="No" />
		</div>
	</form>

<?php else: ?>
	<p>Cannot find pages.</p>
<?php endif;?>
